<?xml version="1.0" encoding="utf-8"?><Database Name="ProjetoPaisesJoaoPires" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ProjetoPaisesJoaoPires.mssql.somee.com;Initial Catalog=ProjetoPaisesJoaoPires;Persist Security Info=True;User ID=joaopires95_SQLLogin_1" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjetoPaisesJoaoPiresConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Information" Member="Informations">
    <Type Name="Information">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Info" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
</Database>